CI
on: [push, workflow_dispatch] jobs:
build:
runs-on: windows-latest steps:
- name: Download
- name: Extract
run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
run: Expand-Archive ngrok.zip
run: - \ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
10835-0
NGROK_AUTH_TOKEN: $(secrets.NGROK_AUTH_TOKEN))
- name: Enable TS
name: Downloa Value e
run: Set-ItemProperty-Path 'HKLM: \System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections"
- run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
run: Set-ItemProperty -Path HKLM: \System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name
"UserAuthentication"
-Value 1
- run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@sswOrd!" -Force)
- name: Create Tunnel
run: -\ngrok\ngrok.exe tcp 3389
